name: Build, test, and push container image to docker hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build container image
      run: docker build -t node-hello-test .

    - name: Run container
      run: |
        docker run -d -p 3000:3000 --name nodehello-instance node-hello-test
        sleep 2

    - name: Test HTTP Response
      run: curl --fail http://localhost:3000 | grep -i 'Hello'

    - name: Clean up container
      if: always()
      run: |
        docker stop nodehello-instance
        docker rm nodehello-instance
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Tag & Push image to Docker Hub
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/node-hello
        GIT_SHA=$(echo ${{ github.sha }} | cut -c1-12)    
        docker tag node-hello-test $IMAGE_NAME:$GIT_SHA
        docker tag node-hello-test $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$GIT_SHA
        docker push $IMAGE_NAME:latest
